version: '1'
build:
  steps:
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build
deploy:
  steps:
    - name: Deploy to Zeabur
      run: npx zeabur deploy
